name: Watch Original Repo

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/WatWowMap/wwm-uicons.git
          git fetch upstream
          git log HEAD..upstream/main --oneline > new_commits.txt

      - name: Notify Discord if there are new commits
        run: |
          if [ -s new_commits.txt ]; then
            curl -H "Content-Type: application/json" -X POST \
            -d "{\"content\": \"🚨 New commits in upstream repo:\n$(cat new_commits.txt)\"}" \
            ${{ secrets.DISCORD_WEBHOOK }}
          fi
